# Generated by Django 4.2.2 on 2023-07-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='CodeTerra Coding Blong', max_length=255),
        ),
    ]
