# Generated by Django 4.2.2 on 2023-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0006_alter_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
