# Generated by Django 4.2.2 on 2023-07-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0009_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='basic', max_length=100),
        ),
    ]
