# Generated by Django 4.2.2 on 2023-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0010_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
