# Generated by Django 4.2.2 on 2023-07-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0019_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
